### ISSUE TITLE
Yie Ar Kung Fu - Music/Sound Pitch too high 

### ISSUE THREAD

**Issue by evidencedj** [jotego/jtkicker#4]
Hi,

I have tested Yie Ar Kung Fu on MiSTer and compared it to my original Konami board (GX 407, PWB 200211A) and I have noticed that the sound pitch is way too high from the MiSTer version. I can provide a video comparison if needed. I am well aware that this is still a beta. But wanted to point it out once.

Best regards

ev

**Comment by jotego** [comment]
You're right. I had connected the sound chip to the wrong clock. I have fixed it in commit c071fbb.
I'll update the files in a few minutes. 
Atom in the Alpha test team had actually complained about the pitch but in the midst of other bugs I lost track and didn't look at it. Thank you for reporting it.
